### ISSUE TITLE
Exception while invoking method 'createAccounts'

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#281]
Saw this server exception:

```
Exception while invoking method 'createAccounts' {
  stack: 'Error: Match error: Expected Array
    at check (packages/check/match.js:36:17)
    at MethodInvocation.createAccounts (server/methods/createAccount.coffee:26:3)
    at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/mdg_meteor-apm-agent.js:2617:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)
    at packages/ddp-server/livedata_server.js:559:43',
  source: 'method' }

**Comment by MarvinZeising** [comment]
Seems like this only happens when there is an error at the csv file import
