### ISSUE TITLE
Exception while invoking method 'mergeAccounts'

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#284]
Saw this server exception:

```
Exception while invoking method 'mergeAccounts' {
  stack: 'Error: Missing \'roles\' param
    at Object._updateUserRoles (packages/alanning_roles.js:685:23)
    at Object.addUsersToRoles (packages/alanning_roles.js:221:11)
    at MethodInvocation.mergeAccounts (both/methods/user/userPermissions.coffee:28:11)
    at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/mdg_meteor-apm-agent.js:2617:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)
    at packages/ddp-server/livedata_server.js:559:43',

**Comment by MarvinZeising** [comment]
Exception while invoking method 'mergeAccounts' { stack: 'TypeError: Cannot convert undefined or null to object\n at Function.keys (<anonymous>)\n at MethodInvocation.mergeAccounts (both/methods/user/userPermissions.coffee:27:4)\n at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)\n at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Promise (packages/ddp-server/livedata_server.js:715:46)\n at new Promise (<anonymous>)\n at Session.method (packages/ddp-server/livedata_server.js:689:23)\n at packages/mdg_meteor-apm-agent.js:2617:38\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)\n at packages/ddp-server/livedata_server.js:559:43',
