### ISSUE TITLE
Exception while invoking method 'changePassword'

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#296]
```
Exception while invoking method 'changePassword' {
  stack: 'Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
    at check (packages/check/match.js:36:17)
    at MethodInvocation.changePassword (packages/accounts-password/password_server.js:465:3)
    at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/mdg_meteor-apm-agent.js:2617:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)
    at packages/ddp-server/livedata_server.js:559:43',

**Comment by MarvinZeising** [comment]
Seems to be a normal check, too. Throws an error if the client sends invalid data
