### ISSUE TITLE
vessel.get throws an error

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#318]
https://www.jwmanagement.org/ziyzv/vessels/ybdbPxRvQBwwaF5N9

Exception while invoking method 'vessel.get' { stack: 'TypeError: Cannot read property \'filter\' of undefined\n at getExtendedVisit (imports/api/vessels/service.js:339:34)\n at getExtendedVessel (imports/api/vessels/service.js:374:28)\n at MethodInvocation.vessel.get (imports/api/vessels/service.js:61:12)\n at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)\n at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Promise (packages/ddp-server/livedata_server.js:715:46)\n at new Promise (<anonymous>)\n at Session.method (packages/ddp-server/livedata_server.js:689:23)\n at packages/mdg_meteor-apm-agent.js:2617:38\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)\n at packages/ddp-server/livedata_server.js:559:43',

**Comment by MarvinZeising** [comment]
Seems like this fixed it. The vessel can be opened, now.
