### ISSUE TITLE
getAvailableHarbors sometimes errors

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#319]
Exception while invoking method 'vessel.visit.getAvailableHarbors' { stack: 'TypeError: Cannot read property \'map\' of undefined\n at MethodInvocation.vessel.visit.getAvailableHarbors (imports/api/vessels/service.js:167:8)\n at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)\n at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Promise (packages/ddp-server/livedata_server.js:715:46)\n at new Promise (<anonymous>)\n at Session.method (packages/ddp-server/livedata_server.js:689:23)\n at packages/mdg_meteor-apm-agent.js:2617:38\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)\n at packages/ddp-server/livedata_server.js:559:43',

**Comment by MarvinZeising** [comment]
Seems like this fixed it. The visits can be added without any error showing up in the logs or on the front end.
