### ISSUE TITLE
Exception while invoking method 'cancelParticipation'

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#320]
Exception while invoking method 'cancelParticipation' { stack: '[object Object]\n => awaited here:\n at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)\n at Server.apply (packages/ddp-server/livedata_server.js:1634:14)\n at Server.call (packages/ddp-server/livedata_server.js:1603:17)\n at MethodInvocation.cancelParticipation (both/methods/shift/shiftRequest.coffee:198:13)\n at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)\n at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Promise (packages/ddp-server/livedata_server.js:715:46)\n at new Promise (<anonymous>)\n at Session.method (packages/ddp-server/livedata_server.js:689:23)\n at packages/mdg_meteor-apm-agent.js:2617:38\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)',

**Comment by MarvinZeising** [comment]
can't see any error in the code :-(
