### ISSUE TITLE
Exception while invoking method 'toggleAvailability'

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#325]
Exception while invoking method 'toggleAvailability' { stack: 'TypeError: Array.prototype.indexOf called on null or undefined\n at indexOf (<anonymous>)\n at MethodInvocation.toggleAvailability (both/methods/user/user.coffee:124:32)\n at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)\n at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Promise (packages/ddp-server/livedata_server.js:715:46)\n at new Promise (<anonymous>)\n at Session.method (packages/ddp-server/livedata_server.js:689:23)\n at packages/mdg_meteor-apm-agent.js:2617:38\n at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)\n at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)\n at packages/ddp-server/livedata_server.js:559:43',

**Comment by MarvinZeising** [comment]
TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (<anonymous>)
    at MethodInvocation.toggleAvailability (both/methods/user/user.coffee:124:32)
    at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/mdg_meteor-apm-agent.js:2617:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)
    at packages/ddp-server/livedata_server.js:559:43
